### ISSUE TITLE
geodesic distance (or euclidean distance)

### ISSUE THREAD

**Issue by yu-to-msk** [iyerkrithika21/mesh2SSM_2023#1]
Thank you for your great research with codes.
I have a question.
Does the mesh-AE model need to input indices based on geodesic distance in the test phase?

particles,reconstruction = model(data) # => model(data,idx)

Thank you.

**Comment by iyerkrithika21** [comment]
Thanks for your interest in our work. 

Yes, the indices need to be passed for the test phase as well.

**Comment by yu-to-msk** [comment]
Thank you for your answer. I see. It is an amazing work.
I have additional questions.

1) Output dimension of IM-Net
In the paper, "For Mesh2SSM template, we use 256 points uniformly spread across the surface..."
Does it mean the template mesh (corresponding points C) has 256 vertices?
and in my investigation of this code, corresponding points C (m x 3) dimension of IM-Net is the same as output points C^ (M x 3) dimension of P-VAE, is that correct? (e.q. m=M=256?)
Is there a relationship between m and m in z^m? (If yes, m=32 in the box-bump dataset experiment?
How did you decide to m? (target structure-dependent?

2) Re-try box-bump experiment
I generated my own box-bump dataset as a test. (Is the box-bump dataset used in your paper publicly available? I couldn't find it.
But it doesn't work with our box-bump dataset.
If possible, could you share us the detailed (hyper-)parameters of an experiment of the box-bump dataset?

I have been investigating the IM-Net settings.
In this paper, nf=8 but nf=128 in the original IM-Net paper.

Thank you.

**Comment by iyerkrithika21** [comment]
Hello, 
I will try to provide a detailed response along with the box bump dataset by the 19th. 
I apologize for taking so long to reply.

**Comment by iyerkrithika21** [comment]
1. Output dimension of IM-Net

> In the paper, "For Mesh2SSM template, we use 256 points uniformly spread across the surface..."
> Does it mean the template mesh (corresponding points C) has 256 vertices?

Yes, the template is a point cloud with 256 points so you can consider it as a mesh with 256 vertices. 

> and in my investigation of this code, corresponding points C (m x 3) dimension of IM-Net is the same as output points C^ (M x 3) dimension of P-VAE, is that correct? (e.q. m=M=256?)

P-VAE is a variational autoencoder on the learned correspondences C. Hence, the input and output dimensions are the same (autoencoding feature). 
The shape-VAE works on the output of the correspondence generation module. 

> Is there a relationship between m and m in z^m? (If yes, m=32 in the box-bump dataset experiment?
> How did you decide to m? (target structure-dependent?

z^m is just the notation (m stands for mesh) to differentiate between the latent space of the mesh-autoencoder in the correspondence generation module and the latent space z^p (p stands for particles) of the shape-VAE in the analysis module. 


2. Box bump generation code added to the repository. 
You will need to install `pyvista` and [`shapeworks`](https://github.com/SCIInstitute/ShapeWorks)
However, if you can smooth the meshes with any other software, then `shapeworks` won't be required. 

Hyperparameters of box bump experiments: 
`batch_size=10, test_batch_size=10, epochs=100, use_sgd=False, lr=0.01, momentum=0.9, seed=42, dropout=0.5, emb_dims=32, nf=8, k=10,  mse_weight=0.01`

3. IM-Net 

> I have been investigating the IM-Net settings.
> In this paper, nf=8 but nf=128 in the original IM-Net paper.

We use different nf values for the different datasets. Since box-bump is a simple dataset, nf=32 is sufficient. For more complex datasets you can increase the nf value.

**Comment by yu-to-msk** [comment]
Thank you for your reply.
I will investigate and retry it, deeply.

**Comment by yu-to-msk** [comment]
Sorry, I’d like to get a better understanding of template mesh creation.
In the paper, "For Mesh2SSM template, we use 256 points uniformly spread across the surface... "

How did you create a template mesh(/point cloud)? I will do that, is it correct? (But the output mesh is not with uniformly spread vertices, in my check.
import shapeworks as sw
sw_mesh = sw.Mesh(medoid_or_sphere_file_with_2000_vertices)
sw_mesh.remesh(numVertices=256, adaptivity=0.0)
sw_mesh.write(out_template_file)

Thank you.

**Comment by iyerkrithika21** [comment]
If the shape is complex, the adaptivity might have to be tuned to get a better spread of particles. 
Alternatively, you could open a few (two shapes should be good enough; you can repeat shapes) meshes in ShapeWorksStudio (drag and drop the shapes into Studio) -> skip grooming -> save project -> go to the optimization tab -> set optimizing iterations to zero -> set initialization iterations -> run optimize -> save project again. 
The resulting particle files can be used as a starting template.

**Comment by yu-to-msk** [comment]
Thank you for your prompt reply.
I have never used Shapeworks (including studio and Python interface), so thank you for the useful information.
Sorry for an additional question, how did you get faces (vertices connectivity) from particles? (Off course, it might be possible to calculate the faces from the vertices in scratch, if that's possible, it might not be a problem. 

Thank you.

**Comment by iyerkrithika21** [comment]
Your template point cloud does not need the faces. The template point cloud is only the input to IM-Net which only has - x,y,z co-ordinate for each point/particle. 
Your input meshes, which are passed to the mesh autoencoder, have - vertices and edges.

**Comment by yu-to-msk** [comment]
Thank you for your prompt reply.

I understood. But I have some confuse.
It could convert particles to mesh to get final result of corresponding mesh?
In Fig.1 ("Fig. 1. Top two PCA modes of variations identified ..."), 
I can see colored points (as particles) and deformed yellow box-bump meshes.
A yellow box-bump shape was created from the particle placement, in my understanding, is it correct?

Thank you.

**Comment by iyerkrithika21** [comment]
For the PCA modes, you can reconstruct the meshes using the particles.
You can use online tools to construct the meshes from the predicted particles or use ShapeWorks to analyze the generated model. 

Added a code - `generate_project.py`, which you can use as a project file for ShapeWorks and open the project in Studio, which will automatically reconstruct the meshes and help you analyze the PCA modes in the analysis tab.

**Comment by yu-to-msk** [comment]
Thank you for your reply.
I understood to reconstruct meshes from the predicted particles using ShapeWorks.
I would like to deeply understand this code and shapeworks.

Thank you
