### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by chensjtu** [iyerkrithika21/mesh2SSM_2023#2]
hello, I wonder how can I get the dataset you used in the meshssm?

**Comment by iyerkrithika21** [comment]
For the toy example, you can use this code to generate the box-bump dataset: 
https://github.com/iyerkrithika21/mesh2SSM_2023/blob/main/boxbump_generation.py

The pancreas dataset is from [Medical Segmentation Decathlon](http://medicaldecathlon.com/) Dataset, which is a public dataset. 
It consists of pancreas segmentations, which are converted to meshes for this project.

**Comment by chensjtu** [comment]
Many Thanks for your quick reply! As you mentioned ``It consists of pancreas segmentations, which are converted to meshes for this project'', while the meshes used in meshSSM should be pre-processed, i.e., centered, aligned, smoothed, and should roughly contain the same number of vertices and edges. I wonder how can I preprocess these meshes? Is there any repo or code can help me to generate meshes qualify the meshSSM's requirements?

**Comment by iyerkrithika21** [comment]
I will provide an update with comments soon. 
Working on sharing the data and making it public.

**Comment by chensjtu** [comment]
That's great! Many thanks for your efforts!

**Comment by iyerkrithika21** [comment]
@chensjtu: I have updated the readme and added the code to download the dataset.
